version: 2.1

orbs:
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@2.3.0

# Commands - reusable sets of steps
commands:
  maven_install:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

jobs:
  secrets_scan_local:
    docker:
      - image: zricethezav/gitleaks:latest
    steps:
      - checkout
      - run:
          name: Run gitleaks scan (local files only)
          # --source . : scan current directory and all subdirectories
          # --no-git : do not scan git history
          command: gitleaks detect --source . --no-git
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - maven_install
      - run:
          name: Build Package
          command: mvn clean package -DskipTests
      - persist_to_workspace:
          root: .
          paths:
            - target/
            - Dockerfile
            - .dockerignore
            - .mvn/
            - mvnw
            - mvnw.cmd
            - pom.xml
            - src/

  # Snyk Static Application Security Testing (code scan)
  snyk_sast:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - maven_install
      - run:
          name: Make Maven wrapper executable
          command: chmod +x ./mvnw
      - snyk/scan:
          command: code test
          fail-on-issues: false
          severity-threshold: medium


  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - maven_install
      - run:
          name: Run Tests
          command: mvn test

  scan:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - setup_remote_docker
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - run: docker build -t $DOCKER_IMAGE .
      - snyk/scan:
          docker-image-name: $DOCKER_IMAGE
          fail-on-issues: false
          severity-threshold: medium

  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: << pipeline.git.revision >>,latest
      - docker/push:
          image: $DOCKER_IMAGE
          tag: << pipeline.git.revision >>,latest

workflows:
  workflow-develop:
    jobs:
      - secrets_scan_local:
          filters:
            branches:
              only: develop
      - build:
          filters:
            branches:
              only: develop
      - test:
          requires:
            - build
          filters:
            branches:
              only: develop
      - snyk_sast:
          requires:
            - build
          filters:
            branches:
              only: develop
      - scan:
          requires:
            - build
          filters:
            branches:
              only: develop
      - publish:
          requires:
            - test
            - scan
          filters:
              branches:
                only: develop